backend:
  name: github
  repo: DataCueCo/datacue-help
media_folder: "docs/.vuepress/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "docs/README.md"
        delete: false
        fields:
          - { label: "Home", name: "home", widget: "hidden", default: true }
          - {
              label: "Hero image",
              name: "heroImage",
              widget: "image",
              required: true,
            }
          - { label: "Action text", name: "actionText", widget: "string", default: Get Started → }
          - { label: "Action link", name: "actionLink", widget: "string", default: /#getting-started }
          - {
              label: "Footer",
              name: "footer",
              widget: "string",
              required: true,
              default: "© 2018-present DataCue (PTE. LTD.)"
            }
          - { label: "Body", name: body, widget: markdown, required: false }
  - label: "Guide"
    name: "guide"
    folder: "docs/guide"
    create: false
    identifier_field: summary
    filter: {field: "blog_index", value: false}
    fields:
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Install"
    name: "install"
    folder: "docs/install"
    create: false
    filter: {field: "blog_index", value: false}
    fields:
      - { label: "Position", name: "position", widget: "number" }
      - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Home (ES)"
    name: "home-es"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "es/docs/README.md"
        delete: false
        fields:
          - { label: "Home", name: "home", widget: "hidden", default: true }
          - {
              label: "Hero image",
              name: "heroImage",
              widget: "image",
              required: true,
            }
          - { label: "Action text", name: "actionText", widget: "string", default: Get Started → }
          - { label: "Action link", name: "actionLink", widget: "string", default: /#getting-started }
          - {
              label: "Footer",
              name: "footer",
              widget: "string",
              required: true,
              default: "© 2018-present DataCue (PTE. LTD.)"
            }
          - { label: "Body", name: body, widget: markdown, required: false }
  - label: "Guide (ES)"
    name: "guide-es"
    folder: "es/docs/guide"
    create: false
    identifier_field: summary
    filter: {field: "blog_index", value: false}
    fields:
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Install (ES)"
    name: "install-es"
    folder: "es/docs/install"
    create: false
    filter: {field: "blog_index", value: false}
    fields:
      - { label: "Position", name: "position", widget: "number" }
      - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  # - label: "Guide"
  #   name: "guide"
  #   files:
  #     - label: "Banners"
  #       name: "banners"
  #       file: "docs/guide/banners.md"
  #       delete: false
  #       fields:
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "Products"
  #       name: "products"
  #       file: "docs/guide/products.md"
  #       delete: false
  #       fields:
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "Notifications"
  #       name: "notifications"
  #       file: "docs/guide/notifications.md"
  #       delete: false
  #       fields:
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  # - label: "Install"
  #   name: "install"
  #   files:
  #     - label: "Shopify"
  #       name: "shopify"
  #       file: "docs/install/shopify.md"
  #       delete: false
  #       fields:
  #         - { label: "Position", name: "position", widget: "number" }
  #         - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "WooCommerce"
  #       name: "woocommerce"
  #       file: "docs/install/woocommerce.md"
  #       delete: false
  #       fields:
  #         - { label: "Position", name: "position", widget: "number" }
  #         - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "Prestashop"
  #       name: "prestashop"
  #       file: "docs/install/prestashop.md"
  #       delete: false
  #       fields:
  #         - { label: "Position", name: "position", widget: "number" }
  #         - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "Magento"
  #       name: "magento"
  #       file: "docs/install/magento.md"
  #       delete: false
  #       fields:
  #         - { label: "Position", name: "position", widget: "number" }
  #         - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "Custom"
  #       name: "custom"
  #       file: "docs/install/custom.md"
  #       delete: false
  #       fields:
  #         - { label: "Position", name: "position", widget: "number" }
  #         - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "Advanced"
  #       name: "advanced"
  #       file: "docs/install/advanced.md"
  #       delete: false
  #       fields:
  #         - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "Test Mode"
  #       name: "testmode"
  #       file: "docs/install/testmode.md"
  #       delete: false
  #       fields:
  #         - { label: "Filter", name: "filter", widget: "select", options: ["platform", "advanced"] }
  #         - { label: "Summary", name: "summary", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
